### Register User
POST http://localhost:8000/users/register
Content-Type: application/json

{
  "email": "driver1@example.com",
  "password": "securepassword",
  "full_name": "Nguyen Van A",
  "phone_number": "0901234567"
}

### Login
POST http://localhost:8000/users/token
Content-Type: application/x-www-form-urlencoded

username=driver1@example.com&password=securepassword

> {% client.global.set("auth_token", response.body.access_token); %}

### Get Current User
GET http://localhost:8000/users/me
Authorization: Bearer {{auth_token}}

### Create Emergency Contact
POST http://localhost:8000/contacts/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": " Vo Van B",
  "phone_number": "0909999999"
}

### Get Contacts
GET http://localhost:8000/contacts/
Authorization: Bearer {{auth_token}}

### Start Trip
POST http://localhost:8000/trips/start
Authorization: Bearer {{auth_token}}

> {% client.global.set("trip_id", response.body.trip_id); %}

### 6. Send Detection Log (Auto Trip ID)
POST {{base_url}}/trips/detections
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "event_type": "drowsy",
  "confidence": 0.88,
  "gps_location": "10.762622, 106.660172"
}

### 7. End Trip
POST http://localhost:8000/trips/end
Authorization: Bearer {{auth_token}}

### 8. Statistics - Summary (Overview)
GET {{base_url}}/statistics/summary
Authorization: Bearer {{auth_token}}

### 8b. Statistics - Summary (Filtered)
GET {{base_url}}/statistics/summary?period=TODAY
Authorization: Bearer {{auth_token}}

### 9. Statistics - Driving Durations
GET http://localhost:8000/statistics/durations
Authorization: Bearer {{auth_token}}

### 10. Statistics - Trips (Filtered by Period)
# Modes: TODAY, THIS_WEEK, THIS_MONTH, THIS_YEAR
GET http://localhost:8000/statistics/trips?period=TODAY
Authorization: Bearer {{auth_token}}

### 11. Statistics - Calendar Check-in
GET http://localhost:8000/statistics/calendar?month=12&year=2025
Authorization: Bearer {{auth_token}}

### 12. Forgot Password
POST http://localhost:8000/users/forgot-password
Content-Type: application/json

{
    "email": "driver1@example.com"
}

### 13. Reset Password
POST http://localhost:8000/users/reset-password
Content-Type: application/json

{
    "email": "driver1@example.com",
    "new_password": "newsecurepassword",
    "code": "123456"
}
